# Generated by Django 4.1.7 on 2023-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(default='', unique=True),
        ),
    ]
