# Generated by Django 4.1.7 on 2023-03-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_categories_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, default="", unique=True),
        ),
    ]
