# Generated by Django 4.1.7 on 2023-03-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_course_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.RemoveField(model_name="course", name="categories",),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.category",
            ),
        ),
        migrations.AlterField(
            model_name="course", name="date", field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
