# Generated by Django 4.1.7 on 2023-03-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0007_uploadmodel_remove_course_categories_course_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="category",),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(to="courses.category"),
        ),
    ]
