# Generated by Django 4.1.7 on 2023-03-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_remove_course_categories_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="isHome",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
    ]
