# Generated by Django 4.1.7 on 2023-04-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_course_ishome_alter_course_isactive"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="imageUrl",),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
